punnett -> Latextablemaker
catherinemoresco/PunnetSquareMaker pull request #1
Opened 2017-04-03 18:28 UTC by remyslab

Hi!
Check my version of your punnettsquaremaker, I added a feature to produce Latex tables.

Cheers, 
Rémy, from France.

2017-04-03 19:07 UTC, remyslab commented
I added a python3 version :)

2017-04-04 03:00 UTC, catherinemoresco requested changes
Thanks so much for contributing! LaTex is the best, it's really awesome to have support for that.

2017-04-04 03:00 UTC, catherinemoresco commented on README.md
> +Punnett Square Maker
Would you mind leaving the spaces out of the title?

2017-04-04 03:00 UTC, catherinemoresco commented on punnetsquaremaker.py
> +	f= open(name, 'w')
nit: please use spaces on either side of equals signs (here and in the rest of the files)

https://google.github.io/styleguide/pyguide.html?showone=Whitespace#Whitespace

2017-04-04 03:00 UTC, catherinemoresco commented on punnetsquaremaker.py
> +	f= open(name, 'a')
Please consider making the writing of a LaTex file optional--i.e., giving the user the ability to use the tool from the command line without creating a new file.

2017-04-04 03:00 UTC, catherinemoresco commented on punnetsquaremaker.py
> +def headtex():
Please consider refactoring so the file is only opened/closed once--opening and closing files is a relatively expensive operation. For example, you might want to make these functions return strings, and then write them to the file all at once in the main loop.

https://stackoverflow.com/questions/11349020/python-file-open-close-everytime-vs-keeping-it-open-until-the-process-is-finishe

2017-04-04 03:00 UTC, catherinemoresco commented on punnetsquaremaker.py
> +	print 'Your Latex file ' + name + ' is saved in your script repertory !\n'
nit: remove spaces between words and exclamation points, here and below.

2017-04-04 05:34 UTC, remyslab commented on README.md
> +Punnett Square Maker
Ok for "PunnetSquareMaker".

2017-04-04 05:35 UTC, remyslab commented on punnetsquaremaker.py
> +def headtex():
Ok, I'll fix it asap.

2017-04-04 05:35 UTC, remyslab commented on punnetsquaremaker.py
> +	f= open(name, 'w')
Ok, I'll fix it asap.

2017-04-04 05:36 UTC, remyslab commented on punnetsquaremaker.py
> +	f= open(name, 'a')
Ok, I'll fix it asap.

2017-04-04 05:36 UTC, remyslab commented on punnetsquaremaker.py
> +	print 'Your Latex file ' + name + ' is saved in your script repertory !\n'
Ok, I'll fix it asap.

2017-04-04 05:45 UTC, remyslab commented
Thank you Catherine, this's my first contribution with a Github repo (and also I've just few skills in coding...). Your review is appreciated, it makes me better for the next time :)
I'll fix your request as soon as possible and and try to make a new pull request.
Rémy

2017-04-05 17:33 UTC, remyslab commented
Done, I hope there aren't mistakes?

2017-04-06 02:16 UTC, catherinemoresco approved these changes

2017-04-06 02:18 UTC, catherinemoresco commented
Thanks Remy! Looks good. Congrats on your first pr! :)

2017-04-06 02:18 UTC, merged